### ISSUE TITLE
readFile calls callback twice

### ISSUE THREAD

**Issue by kpenfound** [harrisiirak/webhdfs#10]
hdfs.readFile('/path/to/file', function(err, content) { console.log('RETURNED'); });

readFile seems to call callback twice: once with an error for file not found, and once without an error and a valid buffer.

It appears that the finish event is being fired more than once.

**Comment by harrisiirak** [comment]
Hey! Thank you for reporting, gonna look this later.

**Comment by harrisiirak** [comment]
I'm unable to reproduce it myself. Can you give me some more details regarding this?

BR

**Comment by moshewe** [comment]
maybe it's another request-event-handling like bug?

**Comment by kpenfound** [comment]
I believe it was related to the error handling in createReadStream, possibly under uncertain network conditions.
<code>
req.on('error', function (err) {
   req.emit('finish');
});

req.on('complete', function (err) {
   req.emit('finish');
});
</code>

Is it possible for a readStream to encounter an error and finish?

**Comment by zxpan** [comment]
had a same issue. It is easy to reproduce it if a non-existant file is requested.
