### ISSUE TITLE
On Finish callback calls each time

### ISSUE THREAD

**Issue by siraj1044** [harrisiirak/webhdfs#14]
How can we identify if file is successfully uploaded because on finish callback calls each time there is error or file is uploaded successfully.

**Comment by tiagopadua** [comment]
I'm having the same problem here.

I'm trying to append some data to a file, but if the file does not exists, the lib just emits the "finish" event, without any parameter change (comparing with successful requests, when the file exists).
Then, **after** the finish, it emits an "error" event.

How am I supposed to know when it was successful?

**Comment by tiagopadua** [comment]
Looking at the code, I managed to resolve this by adding a parameter on finish event. This parameter contains the error (if any).
Tried locally, it works great in all cases I tested.

I've opened a pull request.
https://github.com/harrisiirak/webhdfs/pull/16

Please check it, the tests are passing.

**Comment by harrisiirak** [comment]
@siraj1044 @tiagopadua can you guys please re-test latest version 1.1.0. This one should resolve issues with missing events.
