### ISSUE TITLE
Calling writeFile not working twice.

### ISSUE THREAD

**Issue by atoztoa** [harrisiirak/webhdfs#15]
I am trying to append to a file.

```
hdfs.writeFile('/loginput/log.txt', "XYZ", true, function(err) {
    if(err) {
        console.log("ERROR");
        console.log(err);
    }
});
  
hdfs.writeFile('/loginput/log.txt', "PQR", true, function(err) {
    if(err) {
        console.log("ERROR");
        console.log(err);
    }
});
```
I was expecting XYZPQRXYZPQR... but getting only XYZXYZ.

The issue seems to because of the pipe being open after the write is complete. I tried creating a new client to the same HDFS, still the same result.

**Comment by harrisiirak** [comment]
@atoztoa can you provide me a full example of your code?

**Comment by harrisiirak** [comment]
@atoztoa also HDFS doesn't support concurrent writes.

http://stackoverflow.com/questions/6389594/is-it-possible-to-append-to-hdfs-file-from-multiple-clients-in-parallel
