### ISSUE TITLE
Piping from tar packing to webhdfs error

### ISSUE THREAD

**Issue by metrotyranno** [harrisiirak/webhdfs#18]
http://stackoverflow.com/questions/39439759/nodejs-piping-from-tar-packing-to-webhdfs-error

Having this issue, caused by \lib\webhdfs.js:588:9

Any thoughts?

**Comment by harrisiirak** [comment]
@metrotyranno as I understand your issue got sorted out?

**Comment by metrotyranno** [comment]
Yes, Issue is sorted.

The TAR packing was failing, changing to tar-fs fixed it.

**Comment by harrisiirak** [comment]
@metrotyranno good to hear
