### ISSUE TITLE
Problem when piping an expressjs request into a writable stream

### ISSUE THREAD

**Issue by yeiniel** [harrisiirak/webhdfs#19]
I'm facing a problem when i try to pipe a Express.js request into a webhdfs writable stream. Apparently the request gets stalled and never ends. I attach the code i'm using below:

```
post(req, res, next) {
        // perform basic content negotiation check to avoid invoke de backend
        // unnecessary
        if (!req.is("text/csv")) {
            res.status(415).end();
            return;
        }

        let destination = this.fs.createWriteStream(
            `/tmp/data.csv`
        );

        destination.on("error", (err) => { console.log(err.message); next(err); });
        destination.on("finish", () => res.status(201).end());

        req.pipe(destination);

        req.on("end", () => console.log("end"));
    }
```

**Comment by harrisiirak** [comment]
@yeiniel this issue is still relevant? Gonna check this when I've some time. Sorry about the delay.

**Comment by yeiniel** [comment]
hello @harrisiirak. I spend some time trying to debug my code and didn't found a solution. Then i replace the use of webhdfs  by a normal http client (request) and the issue go away. I don't know if it is related but one of my findings was that every time a request was made to the WebHDFS API on the name node a redirect response was returned directing the client into a data node. I'm not a WebHDFS expert and i don't know if this is the normal behavior. Apart from that i didn't find anything else strange.

If you are interested i can take some time and test again and elaborate a more detailed explanation of the use case. Because i'm really interested in using a fs like api instead of the HTTP client :). I was using Hortonworks Sandbox for testing purposes.

Best regards
Yeiniel

**Comment by harrisiirak** [comment]
@yeiniel yes, that would be nice
