### ISSUE TITLE
upload to remote hdfs with webhdfs failed from host which hasn't been installed with hdaoop

### ISSUE THREAD

**Issue by gq17** [harrisiirak/webhdfs#25]
I write a JS script to upload data to hdfs with webhdfs.
It works fine if the script runs in the host installed with Hadoop, if the Hadoop is installed in other host, it will show: **Error: connect ECNNREFUSED 127.0.0.1:50075** (I do change the host when creating the webhdfs client)

**Comment by harrisiirak** [comment]
@gq17 hi! Can you give me any example code that produces such behaviour?

**Comment by gq17** [comment]
@harrisiirak considering Hadoop(HDFS) is install in a host(192.168.1.90), I run the script below on this host, it works fine.
```
const WebHDFS = require('webhdfs')

var hdfs = WebHDFS.createClient({
  user:'guoqiang',
  //host:'127.0.0.1',
  //port:'50070',
  //path:''
}, {
  headers: {
    Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MS"
  }
});

const localFilePath = "/home/guoqiang/Downloads/udisk";
const remoteFilePath = "/home/guoqiang/test4"

var upload_hdfs = function(){
  hdfs.exists(remoteFilePath, function (err, exist) {
    function callback(err) {
      if (err){
        console.log("task failed " + err)
      }
      else{
        console.log("ok")
      }
    }
    if(err){console.log('error '+ err)}
    if (exist) {
      console.log("append")
      hdfs.appendFile(remoteFilePath, localFilePath, callback);
    }else {
      console.log("write")
      hdfs.writeFile(remoteFilePath, localFilePath, callback);
    }
  });
}

upload_hdfs();  
``` 

then I run the script on another host, I change the  webhdfsclient configuration

```
var hdfs = WebHDFS.createClient({
  user:'guoqiang',
  host:'192.168.1.90',
  //port:'50070',
  //path:''
}, {
  headers: {
    Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MS"
  }
});
```
then I got the error
```
error true
write
task failed Error: connect ECONNREFUSED 127.0.0.1:50075
```

seems it connect the local Hadoop

**Comment by gq17** [comment]
@harrisiirak the problem is due to network DNS, the host installed with Hadoop needs to be configured(the configuration of Hadoop ) to send back the right hostname and the hostname needs to be recognized by the client host.
ref: http://hadoop.apache.org/docs/r1.0.4/webhdfs.html#CREATE
