### ISSUE TITLE
writeFile not returning errors to callback

### ISSUE THREAD

**Issue by Zambonilli** [harrisiirak/webhdfs#5]
The writeFile method is not returning any errors to the client callback.  I stepped through the code and it looks like the remoteStream.on('error') function (line 414) is being called after the remoteStream.on('finish') (line 418).  This is causing the finish to call the callback w/o the error.

Steps to reproduce:
1.) create webHDFS client object with the host option pointed to a non-existing HDFS instance
2.) call hdfs.writeFile
3.) validate the error variable returned is null

**Comment by moshewe** [comment]
Same happened for me.
In the request package documentation it says to always listen for errors before piping.

**Comment by harrisiirak** [comment]
Resolved by #12
