### ISSUE TITLE
exists not returning errors

### ISSUE THREAD

**Issue by Zambonilli** [harrisiirak/webhdfs#6]
The exists method is not returning errors to the client and defaulting to false if an error is returned from HDFS.  This should return the error to the client so the client can decide how it wants to handle the error as opposed to burying it.

I'll try and get a PR for these tickets.

**Comment by harrisiirak** [comment]
This is basically same for the `fs.exists()` which is also returning the status, not the details itself. For details I recommend to use `stat()` method.

BR
