### ISSUE TITLE
WritableStream gets reset after pipe()

### ISSUE THREAD

**Issue by ajaxx** [harrisiirak/webhdfs#8]
I think there was a change to the streamable behavior.  Basically, the following occurs:

<pre>
var localFileStream = fs.createReadStream('/path/to/local/file');
var remoteFileStream = hdfs.createWriteStream('/path/to/remote/file');
localFileStream.pipe(remoteFileStream);
</pre>

Inside WebHDFS.prototype.createWriteStream(), we attach to the 'pipe' event.  This unwinds the source with src.unpipe(req), save and pause the stream.  The problem is that the in stream_readable.js, there is something akin to the following:

<pre>
  dest.emit('pipe', src);

  // start the flow if it hasn't been started already.
  if (!state.flowing) {
    debug('pipe resume');
    src.resume();
  }
</pre>

The emit makes sense and is where we receive the 'pipe' event.  The pause() sets the state.flowing to false.  And then once the emitted event handler finishes, the second half of that block is invoked.  This re-enables event flow within the source.  Basically, this breaks the detach/reattach model.

The simple workaround is for the author to pause the stream immediately after calling pipe.

So, 

<pre>
rstream.pipe(wstream);
rstream.pause();
</pre>

**Comment by harrisiirak** [comment]
Hey Aaron!

Will look into this. Thanks!

**Comment by harrisiirak** [comment]
@ajaxx let me know how this fix works for you. If there are any new regression regarding this I need to look much deeper.
