### ISSUE TITLE
Getting SSL connection options through to request

### ISSUE THREAD

**Issue by rambler** [harrisiirak/webhdfs#9]
We're having trouble figuring out how to get SSL options (such as described here: https://github.com/request/request#tlsssl-protocol) through to the request module. Basically we've got an SSL port on our WebHDFS service with a self-signed cert and we'd like to be able to provide the CA certificate or turn of authorization (like `NODE_TLS_REJECT_UNAUTHORIZED=0`, but not global).

I've tried adding the following to both the createClient call and in the third argument of the createWriteStream call, where `ca` is our root certificate:

```
ca: ca, rejectUnauthorized: false, agentOptions: { ca: ca, rejectUnauthorized: false }
```

But nothing seems to work. Is there something I'm missing?

**Comment by harrisiirak** [comment]
Hey Ian!

Currently this module doesn't support request options overriding. Although it could be nice idea provide some extra options when creating a new client instance.
